#!/usr/bin/env python3
"""Generate src/nnue_net.c embedding a network file into the engine binary.

Usage: python3 tools/nnue/embed.py [net.nnue]     (no argument: embed nothing -> classical eval)
"""
import sys
from pathlib import Path

out = Path(__file__).resolve().parents[2] / "src" / "nnue_net.c"
data = Path(sys.argv[1]).read_bytes() if len(sys.argv) > 1 else b""
name = Path(sys.argv[1]).name if len(sys.argv) > 1 else "none"
lines = [f"// Generated by tools/nnue/embed.py from {name}. Do not edit.", "#include <stddef.h>", ""]
lines.append(f"const size_t NNUE_EMBEDDED_SIZE = {len(data)};")
lines.append("const unsigned char NNUE_EMBEDDED[] = {")
for i in range(0, len(data), 24):
    lines.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
if not data:
    lines.append("    0")
lines.append("};")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes embedded)")
